### ISSUE TITLE
Manager.java file reading issue

### ISSUE THREAD

**Issue by odhran456** [Mirkz/7#6]
Doesn't read file: NullPointerException when trying to read.

In the processLine method:

- When sorting by category using 
                         `if(data[2] == "Beverage"){` 
   etc, should use `.equals()` to compare Strings. 
- When sorting by category 
                        
                        if(data[2] == "Beverage"){
			
                        double volume = Double.parseDouble(data[5]);
			
                        newItem = new Drink(data[0], costOfItem, data[1], data[2], volume);
			
                        Inventory inventory = new Inventory();`

   for each category, like data[2], data[3] etc, a new inventory is made every time an item is added:
                       
                       `Inventory inventory = new Inventory();`

**Comment by Cryoscopic-E** [comment]
commit cab8a3fafc25c45560b096aa713a219a097c6b45 resolved the issue
